### PR TITLE
Added Russian Translation

### PR DESCRIPTION
**Pull request by gostsdmitry**

### CODE REVIEW

**Comment by wengxt** [comment]
Hi, the translation for this repo happens on https://explore.transifex.com/fcitx/fcitx/

Please submit the translation there (you need to request join on transifex first).

The translation is sync'ed with cron jobs. Thank you for your support.

**Comment by gostsdmitry** [comment]
> Hi, the translation for this repo happens on https://explore.transifex.com/fcitx/fcitx/
> 
> Please submit the translation there (you need to request join on transifex first).
> 
> The translation is sync'ed with cron jobs. Thank you for your support.

Sorry. It looks like I've already done this translation on Transifex...

**Comment by wengxt** [comment]
Ah, thanks.. I missed this repo in the synchronize setup. @gostsdmitry  sorry for the confusion.

**Comment by gostsdmitry** [comment]
> Ah, thanks.. I missed this repo in the synchronize setup. @gostsdmitry sorry for the confusion.

@wengxt Do not apologize. :)

**Pull request closed without merging**
